FROM fedora:34
LABEL usage='podman -v /path/to/dir/with/resume.json:/srv/resume.json -v /path/to/output:/srv/output/ run resume'

RUN dnf install -y -q chromium bzip2 wkhtmltopdf nodejs npm teckit && \
    useradd nonroot
USER nonroot
ENV PATH=$PATH:$HOME/node_modules/.bin/ \
    HMR_THEMES='positive awesome' \
    JSON_RESUME_THEMES='eloquent papirus flat minimal modern kendall stackoverflow'
WORKDIR /home/nonroot/
RUN  npm install resume-cli hackmyresume fresh-theme-positive jsonresume-theme-minimal jsonresume-theme-modern jsonresume-theme-kendall jsonresume-theme-stackoverflow jsonresume-theme-flat jsonresume-theme-eloquent jsonresume-theme-papirus --unsafe-perm=true --allow-root && \
    printf "#!/bin/bash\nfor theme in eloquent papirus minimal modern flat kendall stackoverflow ${JSON_RESUME_THEMES}; do\n  mkdir -p output/${theme} ;\n  resume export output/${theme}/${theme}-$(date -I) --format pdf --theme ${theme};\ndone\nfor hmr_theme in positive awesome; do\n  mkdir output/${hmr_theme};\n  hackmyresume build resume.json TO output/${hmr_theme}/resume.all -t ${hmr_theme} ;done" > run.sh && \
  chmod +x run.sh
WORKDIR /srv/
ENTRYPOINT /home/nonroot/run.sh
